project:
  type: book
  output-dir: _book-private

book:
  
  chapters:
    - part: "🔒"
      number-sections: false
      chapters:
      - private/exercise-report.qmd
      - private/answers-A01.ipynb
      - private/answers-A02.ipynb
      - private/L06.ipynb 
      - private/L07.ipynb 
      - private/L08.ipynb 
      - private/L09.ipynb 
      - private/L10.ipynb 
      - private/L11.ipynb 
      - private/L12.ipynb 
      - private/L13.ipynb 
      - private/L14.ipynb 