project:
  type: book
  output-dir: _book-private

book:
  
  chapters:
    - private/exercise-report.qmd

    - part: "🔒 Lectures"
      number-sections: false
      chapters:
      - private/L08.ipynb 
      - private/L09.ipynb 
      - private/L10.ipynb 
      - private/L11.ipynb 
      - private/L12.ipynb 
      - private/L13.ipynb 
      - private/L14.ipynb 
  
    - part: "🔒 Assignments"
      number-sections: false
      chapters:
      - private/answers-A01.ipynb
      - private/answers-A02.ipynb

    - part: "🔒 Problem classes"
      number-sections: false
      chapters:
      - exercises/Problem classes/PC1.ipynb