# List of exercises

Below is a list of all the exercises across all lectures:


## Lecture 1

::: {.exercise-box}
**@exr-1**


Add a new markdown cell below this one and write "Hello world!" 

:::


::: {.exercise-box}
**@exr-eta**


Compute $\eta$ for approximating $e$ with $3$, $2.7$, and $2.718$.

:::


::: {.exercise-box}
**@exr-rate-1**


Show that $\frac{n + \cos(n)}{n^2} = O(\frac1n)$ and $\frac{n^2+3}{n^{42}} = O(\frac1{n^{40}})$.

:::


::: {.exercise-box}
**@exr-e: Approximating Euler's constant**


Let $e$ denote Euler's constant.

1. $e_N := \big( 1 + \frac{1}{N} \big)^N$ is an approximation $e$. What is the error, absolute error, and relative error in approximating $e$ with $e_N$ for $N = 1,2,...,10$? What are the number of accurate digits in this approximation?
2. What is the rate of convergence of $e_N$ to $e$?

:::


::: {.exercise-box}
**@exr-Euler-Mascheroni: Approximating Euler-Mascheroni constant**


Euler-Mascheroni constant, $\gamma$, is defined as the limit of $\gamma_n = \sum_{k=1}^n \frac{1}{k} - \log n$ as $n \to \infty$. 

1. What is the absolute error in approximating $\gamma$ with $\gamma_{1000}$?
2. What is the rate of convergence of $\gamma_n$ to $\gamma$?
3. [This was just so that we can remember some calculus and also rigorously prove the rate of convergence that we have seen above using a rigorous error estimate]  
   Prove that $|\gamma - \gamma_n| \leq \frac1n$.
   
:::



## Lecture 2

::: {.exercise-box}
**@exr-jam**


In England, when we need to convert between lb and kg some people use the phrase "2.2 pounds of jam is the same as a kilogram". 

- What is the error, absolute error, and relative error of approximating 1 kg with 2.2 lb? 
- To how many significant digits is this approximation correct to?

You may use 1 kg = 2.20462262185 lb.

:::


::: {.exercise-box}
**@exr-marathon**


Most people say a marathon is 26 miles when it is actually 26 miles 385 yards. In Europe, people say a marathon is 42 km when it is actually 42.194988 km.

- Which approximation has a smaller error? 
- What is the advantage of computing the relative errors in this case?

Hint: You may use the fact that 1 mile $=$ 1760 yards. 

:::


::: {.exercise-box}
**@exr-AU: Astronomical Unit**


The astronomical unit is defined as $1 \text{AU} = 149,597,870,700 \text{m}$. Write this in standard form. 

:::


::: {.exercise-box}
**@exr-fp-1**


Write down all the floating point numbers with $k = 2$ in the interval $[1,2)$. What about the interval $[2,4)$? $[2^n,2^{n+1})$? 

:::


::: {.exercise-box}
**@exr-fp-3**


Take $k=\ell=2$.

- What number does $0 0 1 1 0$ encode?
- Write the bitstring of $-3.5$.
- What are the maximum and minimum positive numbers and the machine precision in this system?

:::


::: {.exercise-box}
**@exr-fp-2**


What are the maximum and minimum positive numbers and the machine precision for each of ``Float16``, ``Float32``, and ``Float64``?

:::


::: {.exercise-box}
**@exr-Float16-pi**


Write down the bitstring for $\pi$ in ```Float16```.

:::


::: {.exercise-box}
**@exr-cond-2**


Compute the relative condition numbers of (i) $x \mapsto cx$ for $c \not= 0$, (ii) $\log$, (iii) $\exp$, (iv) $x^p$, and (v) $f\circ g$ in terms of $\kappa_f$ and $\kappa_g$

:::



## Lecture 3

::: {.exercise-box}
**@exr-ep-over-2**


Let $\epsilon$ be the machine precision. Is $(1 + \epsilon/2) - 1 = 1 + (\epsilon/2-1)$ in Float64?

:::


::: {.exercise-box}
**@exr-fp-sums**


Let $X$ be an array containing $10^{16}, -10^{16}$, and $N$ copies of $1$. What is the sum of all the entries of the array $X$? Does it depend on the order of summation? What about in ``Float64``? Why?

:::


::: {.exercise-box}
**@exr-FNC-1-4-1**


Exercise 1.4.1 from @fnc 

:::


::: {.exercise-box}
**@exr-FNC-1-4-2**


Exercise 1.4.2 from @fnc.

:::


::: {.exercise-box}
**@exr-change-sign-1**


Let $f(x) = e^x - 2x - 1$. Apply change of sign theorem to $f$ to conclude there exists $\xi \in [1,2]$ such that $f(\xi) = 0$.

:::


::: {.exercise-box}
**@exr-change-sign-2**


Let's return to @exr-change-sign-1. You showed that $f(x) = e^x - 2x - 1$ has a root $\xi \in [1,2]$. 

Show that $f(x) = 0$ can be solved by instead considering the fixed point problems $g(x) = x$ or $h(x) = x$ where

$$
\begin{align}
    g(x) = \log( 2x + 1 ), \quad  \text{and} \quad h(x) = \frac{e^x - 1}{2}
\end{align}
$$ {#eq-L3-g-h}

Show that Brouwer's fixed point theorem applies to $g$ but **not** $h$ on $[1,2]$.

:::


